# Simply store models
FROM alpine:latest as downloader

# Install necessary tools
RUN apk add --no-cache wget

# Create directories for models
RUN mkdir -p /workspace/ComfyUI/models/deepbump /workspace/ComfyUI/models/ipadapter /workspace/ComfyUI/models/clip_vision /workspace/ComfyUI/models/upscale_models /workspace/ComfyUI/models/checkpoints /workspace/ComfyUI/models/vae

# Download models
RUN cd /workspace/ComfyUI/models/deepbump && wget https://github.com/HugoTini/DeepBump/raw/master/deepbump256.onnx
RUN cd /workspace/ComfyUI/models/ipadapter && wget https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors
RUN cd /workspace/ComfyUI/models/clip_vision && wget https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors && \
    mv model.safetensors CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
RUN cd /workspace/ComfyUI/models/upscale_models && wget https://huggingface.co/gemasai/4x_NMKD-Siax_200k/resolve/main/4x_NMKD-Siax_200k.pth
RUN cd /workspace/ComfyUI/models/checkpoints && wget https://huggingface.co/RunDiffusion/Juggernaut-XL-v9/resolve/main/Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors && \
    wget https://civitai.com/api/download/models/456538 -O Juggernaut-XL_inpaint.safetensors
RUN cd /workspace/ComfyUI/models/vae && wget https://huggingface.co/stabilityai/sdxl-vae/resolve/main/sdxl_vae.safetensors
