---
version: "2.0"
services:
  comfyui-custom-models:
    image: spiffgreen/cuda_pytorch_comfyui_jupyter:1.0.0
    expose:
      - port: 8888
        as: 8888
        to:
          - global: true
      - port: 3000
        as: 3000
        to:
          - global: true
    env:
      - JUPYTER_PASSWORD=pass123
    params:
      storage:
        workspace:
          mount: /workspace
          readOnly: false
profiles:
  compute:
    comfyui-custom-models:
      resources:
        cpu:
          units: 4
        memory:
          size: 70GB
        storage:
          - size: 20Gi
          - name: workspace
            size: 70Gi
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 2
          attributes:
            vendor:
              nvidia:
                - model: rtxa6000
                  ram: 48Gi
                  interface: pcie
  placement:
    dcloud:
      pricing:
        comfyui-custom-models:
          denom: uakt
          amount: 1000
deployment:
  comfyui-custom-models:
    dcloud:
      profile: comfyui-custom-models
      count: 1