---
version: "2.0"
services:
  custom-comfyui:
    image: spiffgreen/cuda_pytorch_comfyui_jupyter:latest
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 8888
        as: 8888
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - |-
        #!/bin/bash
        mkdir -p /workspace/ComfyUI/models/ipadapter
        mkdir -p /workspace/ComfyUI/models/deepbump
        mkdir -p /workspace/ComfyUI/models/clip_vision
        mkdir -p /workspace/ComfyUI/models/upscale_models
        mkdir -p /workspace/ComfyUI/models/checkpoints
        mkdir -p /workspace/ComfyUI/models/vae

        cd /workspace/ComfyUI/models/deepbump/
        wget https://github.com/HugoTini/DeepBump/blob/master/deepbump256.onnx


        cd /workspace/ComfyUI/models/ipadapter/
        wget https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.safetensors


        cd /workspace/ComfyUI/models/clip_vision/
        wget https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors
        mv model.safetensors CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors


        cd /workspace/ComfyUI/models/upscale_models/
        wget https://huggingface.co/gemasai/4x_NMKD-Siax_200k/resolve/main/4x_NMKD-Siax_200k.pth


        cd /workspace/ComfyUI/models/checkpoints/
        wget https://huggingface.co/RunDiffusion/Juggernaut-XL-v9/resolve/main/Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors
        wget https://civitai.com/api/download/models/456538 -O Juggernaut-XL_inpaint.safetensors

        cd /workspace/ComfyUI/models/vae/
        wget https://huggingface.co/stabilityai/sdxl-vae/resolve/main/sdxl_vae.safetensors
profiles:
  compute:
    custom-comfyui:
      resources:
        cpu:
          units: 4
        memory:
          size: 60GB
        storage:
          - size: 40Gi
        gpu:
          units: 2
          attributes:
            vendor:
              nvidia:
                - model: rtxa6000
                  ram: 48Gi
                  interface: pcie
  placement:
    dcloud:
      pricing:
        custom-comfyui:
          denom: uakt
          amount: 1000
deployment:
  custom-comfyui:
    dcloud:
      profile: custom-comfyui
      count: 1
